use_sudo = false

[polling]
interval = 5000

[[targets]]
id = "google_http"
group = "external services"
type = "http"
name = "google (http)"
url = "https://www.google.com"

[[targets]]
id = "cloudflare_ping"
group = "external services"
type = "ping"
name = "cloudflare (ping)"
host = "1.1.1.1"

[[targets]]
id = "local_network_arp"
group = "internal network"
type = "arp"
name = "local subnet (arp)"
interface = "eth0"
